use_frameworks!

platform :ios, '13.0'

target 'LLFeedback_Example' do
  pod 'LLFeedback', :path => '../'

#  target 'LLFeedback_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
